import type { QuizQuestion } from "./types";

export const QUESTIONS: QuizQuestion[] = [
  {
    id: "purpose",
    text: "Qual o motivo da sua viagem a Florianópolis?",
    sub: "Isso nos ajuda a te mostrar dicas mais relevantes pra sua viagem.",
    type: "rows",
    options: [
      { emoji: "🏖️", label: "Passeio / Turismo", desc: "Viagem de lazer", value: "passeio" },
      { emoji: "💼", label: "Negócios", desc: "Trabalho na cidade", value: "negocios" },
      { emoji: "🎓", label: "Estudo ou Congresso", desc: "Evento, curso ou faculdade", value: "estudo_congresso" },
      { emoji: "🏃", label: "Atividade Física/Competição", desc: "Treino, prova ou trilha", value: "atividade_fisica" },
      { emoji: "👨‍👩‍👧", label: "Visitar Família/Amigos", desc: "Reencontro por aqui", value: "familia_amigos" },
    ],
  },
  {
    id: "when",
    text: "Quando você vem para Florianópolis?",
    sub: "Assim conseguimos te avisar sobre eventos e a época da sua viagem.",
    type: "rows",
    options: [
      { emoji: "📍", label: "Já estou em Floripa", desc: "Quero o roteiro agora!", value: "chegou" },
      { emoji: "🗓️", label: "Nos próximos 7 dias", desc: "Viagem é essa semana", value: "proximos_7_dias" },
      { emoji: "📆", label: "Entre 2 e 4 semanas", desc: "Ainda tenho um tempinho", value: "2_a_4_semanas" },
      { emoji: "🔭", label: "Daqui a mais de um mês", desc: "Planejando com calma", value: "mais_de_um_mes" },
      { emoji: "🤔", label: "Ainda estou planejando", desc: "Sem data definida", value: "planejando" },
    ],
  },
  {
    id: "region",
    text: "Onde você vai se hospedar?",
    sub: "Isso nos ajuda a montar um roteiro logisticamente inteligente para você.",
    type: "rows",
    optional: true,
    options: [
      { emoji: "🏛️", label: "Centro / Continente", desc: "Próximo ao centro histórico", value: "centro" },
      { emoji: "🌴", label: "Norte da Ilha", desc: "Jurerê, Ingleses, Canasvieiras", value: "norte" },
      { emoji: "🌊", label: "Leste da Ilha", desc: "Lagoa da Conceição, Barra da Lagoa", value: "leste" },
      { emoji: "🌿", label: "Sul da Ilha", desc: "Campeche, Armação, Pântano do Sul", value: "sul" },
      { emoji: "🔍", label: "Ainda não tenho hospedagem", desc: "Me indica uma pousada parceira!", value: "semhospedagem" },
      { emoji: "🤷", label: "Prefiro não informar", desc: "Seguir com roteiro geral", value: "nao" },
    ],
  },
  {
    id: "days",
    text: "Quantos dias você vai ficar em Floripa?",
    sub: "Vamos montar o roteiro certinho para o seu tempo.",
    type: "grid2",
    options: [
      { emoji: "⚡", label: "1 dia", desc: "Só um dia, mas intenso", value: "1" },
      { emoji: "🌅", label: "2 dias", desc: "Um fim de semana perfeito", value: "2" },
      { emoji: "🏝️", label: "3 a 4 dias", desc: "Tempo bom para explorar", value: "3-4" },
      { emoji: "✈️", label: "5 dias ou mais", desc: "Mergulho completo na ilha", value: "5+" },
    ],
  },
  {
    id: "group",
    text: "Como você está viajando?",
    sub: "O roteiro muda bastante dependendo da companhia.",
    type: "grid2",
    options: [
      { emoji: "🙋", label: "Solo", desc: "Na minha", value: "solo" },
      { emoji: "💑", label: "Casal", desc: "A dois", value: "casal" },
      { emoji: "👨‍👩‍👧", label: "Família", desc: "Com crianças", value: "familia" },
      { emoji: "🎉", label: "Amigos", desc: "Em grupo", value: "amigos" },
    ],
  },
  {
    id: "style",
    text: "Qual é o seu estilo de viagem?",
    sub: "Pode escolher mais de um! Escolha tudo que combina com você.",
    type: "grid2",
    multi: true,
    options: [
      { emoji: "🏄", label: "Praia, Surf & Aventura", desc: "Mar, trilhas e natureza", value: "praia" },
      { emoji: "🍽️", label: "Gastronomia", desc: "Comer bem é obrigação", value: "gastronomia" },
      { emoji: "🛍️", label: "Compras", desc: "Shoppings, feiras e lojas", value: "compras" },
      { emoji: "🏛️", label: "Lazer & Cultura", desc: "História, arte e passeios", value: "cultura" },
      { emoji: "🌙", label: "Balada & Bares", desc: "A noite é jovem", value: "noite" },
    ],
  },
  {
    id: "transport",
    text: "Como você vai se locomover?",
    sub: "Isso afeta muito o seu roteiro.",
    type: "rows",
    options: [
      { emoji: "🚗", label: "Tenho carro / moto", desc: "Liberdade total para explorar", value: "carro" },
      { emoji: "📱", label: "Uber / 99", desc: "Prático e sem preocupação", value: "app" },
      { emoji: "🚌", label: "Ônibus / transporte público", desc: "Econômico e sustentável", value: "onibus" },
      { emoji: "🚶", label: "A pé e aluguel eventual", desc: "Curto, exploro devagar", value: "pe" },
    ],
  },
  {
    id: "budget",
    text: "Qual o seu orçamento?",
    sub: "Isso ajuda a sugerir lugares dentro do seu perfil de gasto.",
    type: "rows",
    options: [
      { emoji: "💰", label: "Econômico", desc: "Rolê redondo sem gastar muito", value: "economico" },
      { emoji: "💵", label: "Médio", desc: "Equilíbrio entre custo e conforto", value: "medio" },
      { emoji: "💎", label: "Alto", desc: "Conforto e experiências em primeiro lugar", value: "alto" },
    ],
  },
  {
    id: "special",
    text: "Alguma necessidade especial?",
    sub: "Opcional — mas ajuda a personalizar melhor.",
    type: "rows",
    optional: true,
    options: [
      { emoji: "🦽", label: "Acessibilidade", desc: "Mobilidade reduzida no grupo", value: "acessibilidade" },
      { emoji: "🌱", label: "Vegetariano / vegano", desc: "Preciso de opções plant-based", value: "vegano" },
      { emoji: "👶", label: "Crianças pequenas", desc: "Bebê ou criança até 5 anos", value: "bebe" },
      { emoji: "🐾", label: "Pet friendly", desc: "Viajando com o bichinho", value: "pet" },
      { emoji: "✌️", label: "Nenhuma", desc: "Pode mandar o roteiro normal", value: "nenhuma" },
    ],
  },
];
